/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import helpers.ChiaSeDuLieu;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;

/**
 *
 * @author admin
 */
public class GiaoDienChinh_JFrame extends javax.swing.JFrame {

    private QuanLyBan_JPanel btn_tool_quanLyBan;
    private QuanLyDoUong_JPanel btn_tool_quanLyDoUong;
    private QuanLyNhanVien_JPanel btn_tool_quanLyNhanVien;
    
    private ThongKeHoaDon_JPanel btn_tool_thongKeHoaDon;
    /**
     * Creates new form GiaoDienChinh_JFrame
     */
    public GiaoDienChinh_JFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Trang chủ");
        DangNhapThanhCong();
    }

    public void setLbl_nguoiDung(JLabel lbl_nguoiDung) {
        this.lbl_nguoiDung = lbl_nguoiDung;
    }

    public JLabel getLbl_nguoiDung() {
        return lbl_nguoiDung;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_quanLyDatBan = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btn_quanLyDoUong = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btn_quanLyBan = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btn_thongKe = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        btn_quanLyNhanVien = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btn_dangXuat = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btn_dongTab = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        lbl_nguoiDung = new javax.swing.JLabel();
        lbl_vaiTro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabp_giaoDienChinh = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnu_thoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_gioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_quanLyDatBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-restaurant-menu-50.png"))); // NOI18N
        btn_quanLyDatBan.setText("Quản lý bán hàng");
        btn_quanLyDatBan.setFocusable(false);
        btn_quanLyDatBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyDatBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLyDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyDatBanActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLyDatBan);
        jToolBar1.add(jSeparator6);

        btn_quanLyDoUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-coffee-to-go-50.png"))); // NOI18N
        btn_quanLyDoUong.setText("Quản lý đồ uống");
        btn_quanLyDoUong.setFocusable(false);
        btn_quanLyDoUong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyDoUong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLyDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyDoUongActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLyDoUong);
        jToolBar1.add(jSeparator7);

        btn_quanLyBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-table-50.png"))); // NOI18N
        btn_quanLyBan.setText("Quản lý bàn");
        btn_quanLyBan.setFocusable(false);
        btn_quanLyBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLyBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyBanActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLyBan);
        jToolBar1.add(jSeparator8);

        btn_thongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cash in Hand_50px.png"))); // NOI18N
        btn_thongKe.setText("Thống kê");
        btn_thongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_thongKe);
        jToolBar1.add(jSeparator13);

        btn_quanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-50.png"))); // NOI18N
        btn_quanLyNhanVien.setText("Quản lý nhân viên");
        btn_quanLyNhanVien.setFocusable(false);
        btn_quanLyNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quanLyNhanVien);
        jToolBar1.add(jSeparator9);
        jToolBar1.add(jSeparator10);

        btn_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon-48.png"))); // NOI18N
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.setFocusable(false);
        btn_dangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangXuat);
        jToolBar1.add(jSeparator11);

        btn_dongTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-48.png"))); // NOI18N
        btn_dongTab.setText("Đóng All");
        btn_dongTab.setFocusable(false);
        btn_dongTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dongTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dongTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dongTabActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dongTab);
        jToolBar1.add(jSeparator12);

        jLabel1.setText("Người dùng:");

        jLabel2.setText("Vai trò:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_nguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_vaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_nguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_vaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jToolBar1.add(jPanel1);

        jMenu1.setText("Hệ thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Đăng xuất");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        mnu_thoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        mnu_thoat.setText("Thoát");
        mnu_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_thoatActionPerformed(evt);
            }
        });
        jMenu1.add(mnu_thoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-file-icon-16.png"))); // NOI18N
        jMenuItem3.setText("Quản lý đặt bàn");
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-file-icon-16.png"))); // NOI18N
        jMenuItem4.setText("Quản lý bàn");
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator4);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-file-icon-16.png"))); // NOI18N
        jMenuItem7.setText("Quản lý đồ uống");
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator5);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        jMenuItem8.setText("Thống kê");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-help-about-icon-16.png"))); // NOI18N
        jMenuItem5.setText("Nội dung");
        jMenu3.add(jMenuItem5);
        jMenu3.add(jSeparator3);

        menu_gioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Help-icon-16.png"))); // NOI18N
        menu_gioiThieu.setText("Giới thiệu");
        menu_gioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_gioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(menu_gioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
                    .addComponent(tabp_giaoDienChinh))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabp_giaoDienChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnu_thoatActionPerformed

    /*
        Ngày 21/09/2022 ghi chú bước 7.
        Xử lý sự kiện nhấn nút "Quản lý bàn" thì hiển thị giao diện quản lý bàn ở jtabbed pane
        Dùng if để chỉ tạo 1 lần tránh lặp lại khi click nhiều lần
     */
    private void btn_quanLyBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyBanActionPerformed
        if (btn_tool_quanLyBan == null) {
            btn_tool_quanLyBan = new QuanLyBan_JPanel();
            tabp_giaoDienChinh.addTab("Quản lý bàn", btn_tool_quanLyBan);
        }
        tabp_giaoDienChinh.setSelectedComponent(btn_tool_quanLyBan);
    }//GEN-LAST:event_btn_quanLyBanActionPerformed

    /*
        Ngày 21/09/2022 ghi chú bước 8.
        Xử lý sự kiện nhấn nút "Quản lý đồ uống" thì hiển thị giao diện quản lý bàn ở jtabbed pane
        Dùng if để chỉ tạo 1 lần tránh lặp lại khi click nhiều lần
     */
    private void btn_quanLyDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyDoUongActionPerformed
        if (btn_tool_quanLyDoUong == null) {
            btn_tool_quanLyDoUong = new QuanLyDoUong_JPanel();
            tabp_giaoDienChinh.addTab("Quản lý đồ uống", btn_tool_quanLyDoUong);
        }
        tabp_giaoDienChinh.setSelectedComponent(btn_tool_quanLyDoUong);
    }//GEN-LAST:event_btn_quanLyDoUongActionPerformed

    private void menu_gioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_gioiThieuActionPerformed
        GioiThieu_Dialog gtd = new GioiThieu_Dialog(this, true);
        gtd.setVisible(true);
    }//GEN-LAST:event_menu_gioiThieuActionPerformed

    public DangNhap_Dialog dangnhap;

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        
        dangnhap.getTxt_matKhau().setText("");
        if (dangnhap == null) {
            dangnhap = new DangNhap_Dialog(this, true);
        }
        
        this.setVisible(false);
        dangnhap.setVisible(true);
        // XoaTabbedPane();
        DangNhapThanhCong();
        XoaTabbedPane();
    }//GEN-LAST:event_btn_dangXuatActionPerformed
    /*
        Ngày 23/09/2022 xư lý hiển thị QuanLyNhanVien_JPanel
     */
    private void btn_quanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyNhanVienActionPerformed
        if (btn_tool_quanLyNhanVien == null) {
            btn_tool_quanLyNhanVien = new QuanLyNhanVien_JPanel();
            tabp_giaoDienChinh.addTab("Quản lý nhân viên", btn_tool_quanLyNhanVien);
        }
        tabp_giaoDienChinh.setSelectedComponent(btn_tool_quanLyNhanVien);
    }//GEN-LAST:event_btn_quanLyNhanVienActionPerformed

    private void btn_dongTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dongTabActionPerformed
        XoaTabbedPane();
    }//GEN-LAST:event_btn_dongTabActionPerformed
    private QuanLyBanHang_JPanel btn_tool_quanlyBanHang;
    private void btn_quanLyDatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyDatBanActionPerformed
        // TODO add your handling code here:
        if(btn_tool_quanlyBanHang == null){
            btn_tool_quanlyBanHang = new QuanLyBanHang_JPanel();
            tabp_giaoDienChinh.addTab("Quản lý bán hàng", btn_tool_quanlyBanHang);
        }
        tabp_giaoDienChinh.setSelectedComponent(btn_tool_quanlyBanHang);
    }//GEN-LAST:event_btn_quanLyDatBanActionPerformed

    private void btn_thongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongKeActionPerformed
        // TODO add your handling code here:
        if(btn_tool_thongKeHoaDon == null){
            btn_tool_thongKeHoaDon = new ThongKeHoaDon_JPanel();
            tabp_giaoDienChinh.addTab("Thống kê", btn_tool_thongKeHoaDon);
        }
        tabp_giaoDienChinh.setSelectedComponent(btn_tool_thongKeHoaDon);
    }//GEN-LAST:event_btn_thongKeActionPerformed
    /*
    Xóa all trong tabbed pane
     */
    public void XoaTabbedPane() {

        //tabp_giaoDienChinh.remove(btn_tool_quanLyTaiKhoanChinh);
        tabp_giaoDienChinh.removeAll();
       
        btn_tool_quanLyBan = null;
        btn_tool_quanLyDoUong = null;
        btn_tool_quanLyNhanVien = null;
        btn_tool_quanlyBanHang = null;
        btn_tool_thongKeHoaDon=null;
    }
    
    private void DangNhapThanhCong(){
        lbl_nguoiDung.setText(ChiaSeDuLieu.nguoiDangNhap.getTenDangNhap());
        lbl_vaiTro.setText(ChiaSeDuLieu.nguoiDangNhap.getVaiTro());
        
        if(ChiaSeDuLieu.nguoiDangNhap.getVaiTro().equals("Quản lý")){
            btn_quanLyNhanVien.setEnabled(true);
            btn_quanLyBan.setEnabled(true);
            btn_quanLyDoUong.setEnabled(true);
            btn_quanLyDatBan.setEnabled(false);
            
          
           
        }else if(ChiaSeDuLieu.nguoiDangNhap.getVaiTro().equals("Nhân viên")){
            btn_quanLyNhanVien.setEnabled(false);
            btn_quanLyBan.setEnabled(false);
            btn_quanLyDoUong.setEnabled(false);
            btn_quanLyDatBan.setEnabled(true);
           
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh_JFrame().setVisible(true);
            }
        });
    }
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_dongTab;
    private javax.swing.JButton btn_quanLyBan;
    private javax.swing.JButton btn_quanLyDatBan;
    private javax.swing.JButton btn_quanLyDoUong;
    private javax.swing.JButton btn_quanLyNhanVien;
    private javax.swing.JButton btn_thongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_nguoiDung;
    private javax.swing.JLabel lbl_vaiTro;
    private javax.swing.JMenuItem menu_gioiThieu;
    private javax.swing.JMenuItem mnu_thoat;
    private javax.swing.JTabbedPane tabp_giaoDienChinh;
    // End of variables declaration//GEN-END:variables

    public JTabbedPane getTabp_giaoDienChinh() {
        return tabp_giaoDienChinh;
    }

    public void setTabp_giaoDienChinh(JTabbedPane tabp_giaoDienChinh) {
        this.tabp_giaoDienChinh = tabp_giaoDienChinh;
    }

}
