/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.BanDAO;
import dao.DoDungDAO;
import dao.NhanVienDAO;
import helpers.KiemTraDuLieuNhapVao;
import helpers.ThongBao;
import java.awt.Color;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ban;
import model.DoDung;
import model.NhanVien;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author admin
 */
public class QuanLyDoUong_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyDoUong_JPannel
     */
    public QuanLyDoUong_JPanel() {
        initComponents();
        TaoBang();
        TaiDuLieuLenBang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_idDoDung = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_tenDoDung = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_giaDoDung = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ngayKM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_taoMoi = new javax.swing.JButton();
        btn_themDoDung = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jcp_tbl = new javax.swing.JScrollPane();
        tbl_QLDoDung = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txt_ngayKT = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý đồ uống");

        jLabel2.setText("Mã đồ uống");

        txt_idDoDung.setText("CF1");

        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-icon-16.png"))); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên đồ uống");

        txt_tenDoDung.setText("Cà phê");

        jLabel4.setText("Giá tiền");

        txt_giaDoDung.setText("150000");

        jLabel5.setText("Ngày khuyến mãi");

        txt_ngayKM.setText("2022-10-06");
        txt_ngayKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngayKMActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày kết thúc");

        btn_taoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-icon-16.png"))); // NOI18N
        btn_taoMoi.setText("Nhập mới");
        btn_taoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoMoiActionPerformed(evt);
            }
        });

        btn_themDoDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save-icon.png"))); // NOI18N
        btn_themDoDung.setText("Thêm");
        btn_themDoDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themDoDungActionPerformed(evt);
            }
        });

        btn_capNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        btn_capNhat.setText("Cập nhật");
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        tbl_QLDoDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_QLDoDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_QLDoDungMouseClicked(evt);
            }
        });
        jcp_tbl.setViewportView(tbl_QLDoDung);

        txt_ngayKT.setText("2022-10-07");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_taoMoi)
                            .addComponent(btn_capNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_themDoDung, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel2)))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_ngayKM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                            .addComponent(txt_giaDoDung, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txt_idDoDung, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_timKiem))
                                            .addComponent(txt_tenDoDung, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_ngayKT))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcp_tbl, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_idDoDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_timKiem)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_tenDoDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_giaDoDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ngayKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_ngayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_taoMoi)
                            .addComponent(btn_themDoDung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_capNhat)
                            .addComponent(btn_xoa)))
                    .addComponent(jcp_tbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    /*
    Ngày 05/12/2022 Kiểm tra ngày nhập vào đúng định dạng
    
     */
    public boolean checkDateImport(String date) {
        if (!date.matches("([0-9]{4})-([0-9]{2})-([0-9]{2})")) {
            return false;
        }
        return true;

    }
    private void btn_taoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoMoiActionPerformed
        // TODO add your handling code here:
        txt_idDoDung.setText("");
        txt_tenDoDung.setText("");
        txt_giaDoDung.setText("");
        txt_ngayKM.setText("");
        txt_ngayKT.setText("");
    }//GEN-LAST:event_btn_taoMoiActionPerformed
    private GiaoDienChinh_JFrame giaoDienChinh;
    private void btn_themDoDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themDoDungActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        KiemTraDuLieuNhapVao.KiemTraRong(txt_idDoDung, sb, "Mã đồ dùng không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_tenDoDung, sb, "Tên đồ dùng không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_giaDoDung, sb, "Giá bán đồ dùng không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_ngayKM, sb, "Ngày khuyển mãi không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_ngayKT, sb, "Ngày kết thúc không được để trống");

        if (!checkDateImport(txt_ngayKM.getText())) {
            sb.append("Ngày khuyến mãi phải theo định dạng yyyy-mm-dd\n");
            txt_ngayKM.setBackground(Color.yellow);
            System.out.println(txt_ngayKM.getText());
        } else {
            txt_ngayKM.setBackground(Color.white);
        }

        if (!checkDateImport(txt_ngayKT.getText())) {
            sb.append("Ngày kết thúc phải theo định dạng yyyy-mm-dd\n");
            txt_ngayKT.setBackground(Color.yellow);
            System.out.println(txt_ngayKM.getText());
        } else {
            txt_ngayKT.setBackground(Color.white);
        }

        if (sb.length() > 0) {
            ThongBao.ThongBaoLoi(giaoDienChinh, sb.toString(), "Lỗi");
            return;
        }
        if (ThongBao.ThongBaoXacNhan(giaoDienChinh, "Bạn có muốn lưu \"" + txt_idDoDung.getText() + "\" không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return; // nếu không muốn -> kết thúc sự kiện
        }
        try {

            DoDung dd = new DoDung();
            dd.setIdDoDung(txt_idDoDung.getText());
            dd.setTenDoDung(txt_tenDoDung.getText());
            dd.setGiaDoDung(Float.parseFloat(txt_giaDoDung.getText()));
            dd.setNgayKhuyenMai(Date.valueOf(txt_ngayKM.getText()));
            dd.setNgayKetThuc(Date.valueOf(txt_ngayKT.getText()));

            DoDungDAO ddDAO = new DoDungDAO();
            if (ddDAO.Insert(dd) > 0) { // Insert dữ liệu vào csdl
                ThongBao.ThongBao(giaoDienChinh, "Đồ dùng được lưu thành công", "Thông báo");
                TaiDuLieuLenBang();
            } else {
                ThongBao.ThongBao(giaoDienChinh, "Lưu thất bại", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(giaoDienChinh, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_themDoDungActionPerformed

    private void txt_ngayKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngayKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngayKMActionPerformed

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        KiemTraDuLieuNhapVao.KiemTraRong(txt_idDoDung, sb, "Mã đồ dùng không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_tenDoDung, sb, "Tên đồ dùng không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_giaDoDung, sb, "Giá bán đồ dùng không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_ngayKM, sb, "Ngày khuyển mãi không được để trống");
        KiemTraDuLieuNhapVao.KiemTraRong(txt_ngayKT, sb, "Ngày kết thúc không được để trống");

        if (sb.length() > 0) {
            ThongBao.ThongBaoLoi(giaoDienChinh, sb.toString(), "Lỗi sb.length() > 0");
            return;
        }
        if (ThongBao.ThongBaoXacNhan(giaoDienChinh, "Bạn có muốn cập nhật đồ dùng \"" + txt_idDoDung.getText() + "\" không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return; // nếu không muốn -> kết thúc sự kiện
        }
        try {

            DoDung dd = new DoDung();
            dd.setIdDoDung(txt_idDoDung.getText());
            dd.setTenDoDung(txt_tenDoDung.getText());
            dd.setGiaDoDung(Float.parseFloat(txt_giaDoDung.getText()));
            dd.setNgayKhuyenMai(Date.valueOf(txt_ngayKM.getText()));
            dd.setNgayKetThuc(Date.valueOf(txt_ngayKT.getText()));

            DoDungDAO ddDAO = new DoDungDAO();
            if (ddDAO.Update(dd) > 0) { // Insert dữ liệu vào csdl
                ThongBao.ThongBao(giaoDienChinh, "Đồ dùng được cập nhật thành công", "Thông báo");
                TaiDuLieuLenBang();
            } else {
                ThongBao.ThongBao(giaoDienChinh, "Cập nhật thất bại", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(giaoDienChinh, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        KiemTraDuLieuNhapVao.KiemTraRong(txt_idDoDung, sb, "Mã đồ dùng không được để trống");

        if (sb.length() > 0) {
            ThongBao.ThongBaoLoi(giaoDienChinh, sb.toString(), "Lỗi sb.length() > 0");
            return;
        }
        if (ThongBao.ThongBaoXacNhan(giaoDienChinh, "Bạn có muốn xóa đồ dùng \"" + txt_idDoDung.getText() + "\" không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return; // nếu không muốn -> kết thúc sự kiện
        }
        try {

            DoDung dd = new DoDung(txt_idDoDung.getText());

            DoDungDAO ddDAO = new DoDungDAO();
            if (ddDAO.Delete(dd) > 0) { // Insert dữ liệu vào csdl
                ThongBao.ThongBao(giaoDienChinh, "Đồ dùng được xóa thành công", "Thông báo");
                TaiDuLieuLenBang();
            } else {
                ThongBao.ThongBao(giaoDienChinh, "Xóa thất bại", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(giaoDienChinh, e.getMessage(), "Lỗi");
        }

    }//GEN-LAST:event_btn_xoaActionPerformed

    private void tbl_QLDoDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_QLDoDungMouseClicked
        // TODO add your handling code here:
        try {
            int row = tbl_QLDoDung.getSelectedRow();
            if (row >= 0) { // Người dùng đã chọn 1 dòng trên bảng
                String idDoDung = (String) tbl_QLDoDung.getValueAt(row, 0); // Lấy dữ liệu tại cột đầu

                DoDungDAO ddDAO = new DoDungDAO();
                DoDung doDungID = new DoDung(idDoDung);
                DoDung doDung = ddDAO.selectById(doDungID);

                if (doDung != null) { // Lấy dữ liệu lên khi có chọn 1 dòng có tồn taij mã nhân viên
                    txt_idDoDung.setText(doDung.getIdDoDung());
                    txt_tenDoDung.setText(doDung.getTenDoDung());
                    txt_giaDoDung.setText(String.valueOf(doDung.getGiaDoDung()));
                    txt_ngayKM.setText(String.valueOf(doDung.getNgayKhuyenMai()));
                    txt_ngayKT.setText(String.valueOf(doDung.getNgayKetThuc()));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(giaoDienChinh, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tbl_QLDoDungMouseClicked

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        try {
            DoDungDAO ddDAO = new DoDungDAO();
            DoDung ddID = new DoDung(txt_idDoDung.getText());
            DoDung doDung = ddDAO.selectById(ddID);

            if (doDung != null) {
                txt_idDoDung.setText(doDung.getIdDoDung());
                txt_tenDoDung.setText(doDung.getTenDoDung());
                txt_giaDoDung.setText(String.valueOf(doDung.getGiaDoDung()));
                txt_ngayKM.setText(String.valueOf(doDung.getNgayKhuyenMai()));
                txt_ngayKT.setText(String.valueOf(doDung.getNgayKetThuc()));

            } else {
                ThongBao.ThongBao(giaoDienChinh, "Không tìm thấy mã sinh viên", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(giaoDienChinh, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed
    private DefaultTableModel tblmodel;

    private void TaoBang() {
        tblmodel = new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{"Mã đồ dùng", "Tên", "Giá", "Ngày KM", "Ngày KT"});
        tbl_QLDoDung.setModel(tblmodel);
    }

    private void TaiDuLieuLenBang() {
        try {

            DoDungDAO ddDAO = new DoDungDAO();
            List<DoDung> list = ddDAO.selectAll(); // Trả về all nhân viên trong csdl
            tblmodel.setRowCount(0); // Xóa dữ liệu hiện đang trên bảng
            for (DoDung doDung : list) {
                tblmodel.addRow(new Object[]{
                    doDung.getIdDoDung(), doDung.getTenDoDung(), (int)doDung.getGiaDoDung(),
                    doDung.getNgayKhuyenMai(), doDung.getNgayKetThuc()
                });
            }
            tblmodel.fireTableDataChanged(); // Cập nhật lại hiển thị dữ liệu trong bảng
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(giaoDienChinh, e.getMessage(), "Lỗi");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_taoMoi;
    private javax.swing.JButton btn_themDoDung;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane jcp_tbl;
    private javax.swing.JTable tbl_QLDoDung;
    private javax.swing.JTextField txt_giaDoDung;
    private javax.swing.JTextField txt_idDoDung;
    private javax.swing.JTextField txt_ngayKM;
    private javax.swing.JTextField txt_ngayKT;
    private javax.swing.JTextField txt_tenDoDung;
    // End of variables declaration//GEN-END:variables

}
