/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dao.BanHangDAO;
import dao.HoaDonDAO;
import dao.NhanVienDAO;
import helpers.ChiaSeDuLieu;
import helpers.DatabaseHelper;
import helpers.KiemTraDuLieuNhapVao;
import helpers.ThongBao;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BanHang;
import model.HoaDon;
import model.NhanVien;

/**
 *
 * @author admin
 */
public class ThongKeHoaDon_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeHoaDon_JPanel
     */
    public ThongKeHoaDon_JPanel() {
        initComponents();
        TaoBang();
        TaiDuLieuLenBang_ThongKe();
        TinhDoanhThu();
        PhanQuyenTruyCap();
    }

    private DefaultTableModel tblmodel;
    private GiaoDienChinh_JFrame giaoDienChinh;

    private void TaoBang() {
        tblmodel = new DefaultTableModel();
        tblmodel.setColumnIdentifiers(new String[]{"STT", "Nhân viên", "Tên bàn", "Tổng tiền", "Ngày thanh toán",});
        tbl_thongKe.setModel(tblmodel);
    }

    /*
     Ngày 05/12/2022 Chức năng tính tổng tiền bản thống kê
     */
    public void TinhDoanhThu() {
        try {
            // B1: Tạo kết nối
            Connection con = DatabaseHelper.openConnection();
            // B2: Tạo đối tượng pst + lệnh sql
            String sql = "SELECT SUM(thanhTien) as doanhThu FROM HoaDon ";
            PreparedStatement pst = con.prepareStatement(sql);

            // B3: Thực thi sql
            ResultSet rs = pst.executeQuery();
            // B4: Xử lý dữ liệu
            System.out.println("Ban da thuc thi " + sql);

            while (rs.next()) {

                int doanhThu = (int)rs.getFloat("doanhThu");
                lbl_doanhThu.setText(String.valueOf(doanhThu));

            }
            // B5: Đóng csdl
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void TaiDuLieuLenBang_ThongKe() {
        try {

            HoaDonDAO hoaDonDAO = new HoaDonDAO();
            List<HoaDon> list = hoaDonDAO.selectAll(); // Trả về all nhân viên trong csdl
            tblmodel.setRowCount(0); // Xóa dữ liệu hiện đang trên bảng
            for (HoaDon hoaDon : list) {
                tblmodel.addRow(new Object[]{
                    hoaDon.getMaHoaDon(), hoaDon.getTenDangNhap(), hoaDon.getTenBan(), hoaDon.getThanhTien(),
                    hoaDon.getNgayLap()
                });
            }
            tblmodel.fireTableDataChanged(); // Cập nhật lại hiển thị dữ liệu trong bảng
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBaoLoi(giaoDienChinh, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongKe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbl_doanhThu = new javax.swing.JLabel();
        btn_xoaBangThongKe = new javax.swing.JButton();
        btn_capNhatBangThongKe = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thống Kê Hóa Đơn");

        tbl_thongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_thongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_thongKeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_thongKe);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tổng doanh thu:");

        lbl_doanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_doanhThu.setText("???");

        btn_xoaBangThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        btn_xoaBangThongKe.setText("Xóa");
        btn_xoaBangThongKe.setEnabled(false);
        btn_xoaBangThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaBangThongKeActionPerformed(evt);
            }
        });

        btn_capNhatBangThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        btn_capNhatBangThongKe.setText("Cập nhật");
        btn_capNhatBangThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatBangThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btn_capNhatBangThongKe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_doanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_xoaBangThongKe)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_xoaBangThongKe)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbl_doanhThu)
                        .addComponent(btn_capNhatBangThongKe)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_thongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongKeMouseClicked
        // TODO add your handling code here:
        TaiDuLieuLenBang_ThongKe();
    }//GEN-LAST:event_tbl_thongKeMouseClicked

    private void btn_xoaBangThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaBangThongKeActionPerformed

        // Kiểm tra có muốn xóa hay không 
        if (ThongBao.ThongBaoXacNhan(giaoDienChinh, "Bạn có muốn xóa bảng thống kê không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return; // nếu không muốn -> kết thúc sự kiện
        }
        try {
            // B1: Tạo kết nối
            Connection con = DatabaseHelper.openConnection();
            // B2: Tạo đối tượng pst + lệnh sql
            String sql = "DELETE FROM HoaDon ";
            PreparedStatement pst = con.prepareStatement(sql);

            // B3: Thực thi sql
            int ketQua = pst.executeUpdate();
            // B4: Xử lý dữ liệu
            System.out.println("Ban da thuc thi " + sql);
            System.out.println("Có " + ketQua + " ket qua bi thay doi!!");
            // B5: Đóng csdl
            con.close();
            //DatLaiGiaTriSTT();
            ThongBao.ThongBao(giaoDienChinh, "Xóa bảng thống kê thành công!", "Thông báo");
            TaiDuLieuLenBang_ThongKe();
            lbl_doanhThu.setText("0");
            
        } catch (Exception e) {
            e.printStackTrace();
            ThongBao.ThongBao(giaoDienChinh, "Xóa bảng thống kê thất bại", "Thông báo");
        }
    }//GEN-LAST:event_btn_xoaBangThongKeActionPerformed

    private void btn_capNhatBangThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatBangThongKeActionPerformed
        // TODO add your handling code here:
        TaiDuLieuLenBang_ThongKe();
        TinhDoanhThu();
    }//GEN-LAST:event_btn_capNhatBangThongKeActionPerformed

    private void PhanQuyenTruyCap() {

        if (ChiaSeDuLieu.nguoiDangNhap.getVaiTro().equals("Quản lý")) {

            btn_xoaBangThongKe.setEnabled(true);

        } else if (ChiaSeDuLieu.nguoiDangNhap.getVaiTro().equals("Nhân viên")) {

            btn_xoaBangThongKe.setEnabled(false);
        }
    }

    /*
    private void DatLaiGiaTriSTT() {
        try {
            // B1: Tạo kết nối
            Connection con = DatabaseHelper.openConnection();
            // B2: Tạo đối tượng pst + lệnh sql
            String sql = "UPDATE HoaDon "
                    + " SET maHoaDon=?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            int maHoaDon = 1;
            pst.setInt(1, maHoaDon);

            // B3: Thực thi sql
            int ketQua = pst.executeUpdate();
            // B4: Xử lý dữ liệu
            System.out.println("Ban da thuc thi " + sql);
            System.out.println("Có " + ketQua + " ket qua bi thay doi!!");
            // B5: Đóng csdl
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhatBangThongKe;
    private javax.swing.JButton btn_xoaBangThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_doanhThu;
    private javax.swing.JTable tbl_thongKe;
    // End of variables declaration//GEN-END:variables
}
